FROM ubuntu:18.04 as wedpr_component_vcpkg_cache

LABEL maintainer service@webank.com

WORKDIR /

ARG SOURCE_BRANCH
ENV DEBIAN_FRONTEND=noninteractive \
    SOURCE=${SOURCE_BRANCH:-main}

RUN apt-get -q update && apt-get install -qy --no-install-recommends \
    vim curl git make build-essential cmake  \
    libgmp-dev flex bison patch libzstd-dev unzip ninja-build pkg-config curl zip tar ccache uuid-runtime automake autoconf \
    m4 tcpdump net-tools libkrb5-dev krb5-user pkg-config default-libmysqlclient-dev gcc g++ \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && apt-get install -qy --no-install-recommends tzdata \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

# install rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

ENV VCPKG_FORCE_SYSTEM_BINARIES=1

# first download and compile the vcpkg dependecies
RUN git clone https://github.com/WeBankBlockchain/WeDPR-Component.git --recursive --depth=1 -b ${SOURCE} \
    && mkdir -p WeDPR-Component/cpp/build && cd WeDPR-Component/cpp/build \
    && cmake .. -DBUILD_STATIC=ON \

# move the vcpkg dependecies to /vcpkg
RUN mv /WeDPR-Component/cpp/vcpkg /

