name: Manual trigger vcpkg-cache docker image build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'the input tag'

jobs:
  manual-build-vcpkg-cache-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Fetch tag
        run: |
          git fetch --tags --force
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_FISCOPR_USER }}
          password: ${{ secrets.DOCKER_FISCOPR_TOKEN }}

      # the model image
      - name: Build and Push wedpr-component-vcpkg-cache images
        run: |
          echo "* Manual build wedpr-component-vcpkg-cache image, docker version: ${{ github.event.inputs.tags }}"
          DOCKER_TAG="fiscoorg/wedpr-component-vcpkg-cache:${{ github.event.inputs.tags }}"
          echo "* Begin to build ${DOCKER_TAG}"
          cd docker-files/cpp/vcpkg
          docker build --build-arg SOURCE_BRANCH=${BRANCH_NAME} -t ${DOCKER_TAG} .
          echo "* Build ${DOCKER_TAG} success"
          docker push ${DOCKER_TAG}
          echo "* Push ${DOCKER_TAG} success"
      - name: Publish Error
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autoconf-x64-linux-err.log
          path: /WeDPR-Component/cpp/vcpkg/buildtrees/gsasl/autoconf-x64-linux-err.log